language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ashankasthuri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ashankasthuri/docker-react npm run test